export interface NewFlight{
    FlightNumber : string
    PlaceOfDeparture : string
	PlaceOfArrival : string
	DateOfDeparture : string
	DateOfArrival : string
	TimeOfDeparture : string
	TimeOfArrival : string
	Airline : number
	FlightStatus : string
	EconomyClassPrice : number
	BusinessClassPrice : number
	FirstClassPrice : number
	EconomyClassRemainingSeats : number
	BusinessClassRemainingSeats : number
	FirstClassRemainingSeats : number
	TimeOfBoarding : string
	EconomyClassPoints : number
	BusinessClassPoints : number
	FirstClassPoints : number
}